# Generated by Django 5.2 on 2026-10-03 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pizxifyapp', '0017_alter_album_id_alter_albumpage_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharpness', models.FloatField()),
                ('brightness', models.FloatField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('blur_status', models.CharField(max_length=30)),
                ('brightness_status', models.CharField(max_length=30)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='pizxifyapp.folderphoto')),
            ],
        ),
    ]
