# Generated by Django 5.2 on 2026-10-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoanalysis',
            name='quality_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='photoanalysis',
            name='recommendation',
            field=models.CharField(default='Needs Review', max_length=30),
        ),
    ]
