# Generated by Django 5.2 on 2026-10-03 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0002_photoanalysis_quality_score_and_more'),
        ('pizxifyapp', '0017_alter_album_id_alter_albumpage_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Other', max_length=50)),
                ('scene', models.CharField(default='Unknown', max_length=100)),
                ('photo_type', models.CharField(default='Other', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('group_name', models.CharField(default='Other', max_length=100)),
                ('confidence', models.FloatField(default=0)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_classification', to='pizxifyapp.folderphoto')),
            ],
        ),
    ]
