# Generated by Django 5.2 on 2026-10-03 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0003_photoclassification'),
        ('pizxifyapp', '0017_alter_album_id_alter_albumpage_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_groups', to='pizxifyapp.photofolder')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('face_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='ai_features.facegroup')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_faces', to='pizxifyapp.folderphoto')),
            ],
        ),
    ]
